import Head from "next/head";
import Image from "next/image";

import { type RouterOutputs, api } from "~/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user?.imageUrl}
        alt={`@${user.username}`}
        width={56}
        priority
        height={56}
        className="rounded-full"
      />
      <input
        placeholder="type some emojis!"
        className="grow bg-transparent  outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4 ">
      <Image
        src={author.profilePicture}
        width={56}
        height={56}
        alt="post-image"
        className="rounded-full"
      />
      <div className="flex flex-col ">
        <div className="flex gap-1   text-slate-300">
          <span>
            {`@${author.username}`}
            <span className="font-thin">{`  ·  ${dayjs(
              post.createdAt,
            ).fromNow()}`}</span>
          </span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const user = useUser();

  if (isLoading) return <div>loading...</div>;
  if (!data) return <div>kuch to gadbad hai ...</div>;

  return (
    <>
      <Head>
        <title>twemoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex h-screen justify-center">
        <div className=" h-full w-full  border-x  border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4 ">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col ">
            {[...data]?.map((fullPost) => (
              <PostView key={fullPost.post?.id} {...fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
