import { type NextPage } from "next";
import Head from "next/head";

export const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className=" flex h-screen justify-center">
        <div> </div>
      </main>
    </>
  );
};

export default SinglePostPage;
