name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [21]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print Environment Variable
        run: echo $DATABASE_URL # Changed to DATABASE_URL to match your env variable

